PalestraMongoDB/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MongoDB.Bson;
using Newtonsoft.Json;
using PalestraMongoDB.Domain;
using PalestraMongoDB.Model.Aluno;
using PalestraMongoDB.Model.Disciplina;
using PalestraMongoDB.Repository;

namespace PalestraMongoDB.Controllers
{
	public class AlunoController : Controller
	{
		private IConnectionStringConfiguration connectionStringConfiguration;

		public AlunoController(IConnectionStringConfiguration connectionStringConfiguration)
		{
			this.connectionStringConfiguration = connectionStringConfiguration;
		}

		public async Task<IActionResult> Index()
		{
			var repository = new Repository<Aluno>(connectionStringConfiguration);

			var domains = await repository.Load();
			var models = domains.Select(domain => ToModel(domain));

			return View(models.AsEnumerable());
		}

		public async Task<IActionResult> Edit(string id = null)
		{
			var model = new AlunoModel();

			var alunoRepository = new Repository<Aluno>(connectionStringConfiguration);
			var disciplinaRepository = new Repository<Disciplina>(connectionStringConfiguration);

			if (!string.IsNullOrEmpty(id))
				model = ToModel(await alunoRepository.Get(id));

			var disciplinas = await disciplinaRepository.Load();

			var selectList = new SelectList(disciplinas, "Id", "Nome");
			ViewBag.Disciplinas = selectList;

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(AlunoModel model)
		{
			if (!ModelState.IsValid)
				return View(model);

			var repository = new Repository<Aluno>(connectionStringConfiguration);

			if (string.IsNullOrEmpty(model.Id))
				await repository.Save(ToDomain(model));
			else
				await repository.Update(ToDomain(model));

			return RedirectToAction("Index");
		}

		public async Task<IActionResult> Delete(string id)
		{
			var repository = new Repository<Aluno>(connectionStringConfiguration);

			await repository.Delete(id);

			return RedirectToAction("Index");
		}

		public async Task<IActionResult> AddDisciplina(string id)
		{
			try
			{
				var repository = new Repository<Disciplina>(connectionStringConfiguration);

				var tempDisciplinas = new List<DisciplinaModel>();

				if (TempData.ContainsKey("Disciplinas"))
					tempDisciplinas = TempDeserialize<List<DisciplinaModel>>("Disciplinas");

				if (tempDisciplinas.SingleOrDefault(x => x.Id == id) == null)
				{
					var domain = await repository.Get(id);
					var model = new DisciplinaModel
					{
						Id = domain.Id.ToString(),
						Nome = domain.Nome,
						Duracao = domain.Duracao
					};

					tempDisciplinas.Add(model);
				}

				TempData.Remove("Disciplinas");
				TempData.Add("Disciplinas", TempSerialize<List<DisciplinaModel>>(tempDisciplinas));

				return PartialView("_DisciplinasTable", tempDisciplinas);
			}
			catch (Exception exc)
			{
				return PartialView("_DisciplinasTable");
			}
		}

		private AlunoModel ToModel(Aluno domain)
		{
			return new AlunoModel
			{
				Id = domain.Id.ToString(),
				Nome = domain.Nome,
				Email = domain.Email
			};
		}

		private Aluno ToDomain(AlunoModel model)
		{
			var aluno = new Aluno
			{
				Id = !string.IsNullOrEmpty(model.Id) ? ObjectId.Parse(model.Id) : ObjectId.GenerateNewId(DateTime.Now),
				Nome = model.Nome,
				Email = model.Email
			};

			if (TempData.ContainsKey("Disciplinas"))
			{
				var disciplinasModel = TempDeserialize<List<DisciplinaModel>>("Disciplinas");
				aluno.DisciplinasId = disciplinasModel.Select(disciplinaModel => disciplinaModel.Id).ToList();
			}

			return aluno;
		}

		private string TempSerialize<T>(T serializable)
		{
			return JsonConvert.SerializeObject(serializable);
		}

		private T TempDeserialize<T>(string tempDataKey)
		{
			var tempData = TempData[tempDataKey].ToString();
			return JsonConvert.DeserializeObject<T>(tempData);
		}
	}
}

PalestraMongoDB/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using PalestraMongoDB.Domain;
using PalestraMongoDB.Model.Disciplina;
using PalestraMongoDB.Repository;

namespace PalestraMongoDB.Controllers
{
	public class DisciplinaController : Controller
	{
		private IConnectionStringConfiguration connectionStringConfiguration;

		public DisciplinaController(IConnectionStringConfiguration connectionStringConfiguration)
		{
			this.connectionStringConfiguration = connectionStringConfiguration;
		}

		public async Task<IActionResult> Index()
		{
			var repository = new Repository<Disciplina>(connectionStringConfiguration);

			var domains = await repository.Load();
			var models = domains.Select(domain => ToModel(domain));

			return View(models.AsEnumerable());
		}

		public async Task<IActionResult> Edit(string id = null)
		{
			var model = new DisciplinaModel();

			var repository = new Repository<Disciplina>(connectionStringConfiguration);

			if (!string.IsNullOrEmpty(id))
				model = ToModel(await repository.Get(id));

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(DisciplinaModel model)
		{
			if (!ModelState.IsValid)
				return View(model);

			var repository = new Repository<Disciplina>(connectionStringConfiguration);

			if (string.IsNullOrEmpty(model.Id))
				await repository.Save(ToDomain(model));
			else
				await repository.Update(ToDomain(model));

			return RedirectToAction("Index");
		}

		public async Task<IActionResult> Delete(string id)
		{
			var repository = new Repository<Disciplina>(connectionStringConfiguration);

			await repository.Delete(id);

			return RedirectToAction("Index");
		}

		private DisciplinaModel ToModel(Disciplina domain)
		{
			return new DisciplinaModel
			{
				Id = domain.Id.ToString(),
				Nome = domain.Nome,
				Duracao = domain.Duracao
			};
		}

		private Disciplina ToDomain(DisciplinaModel model)
		{
			return new Disciplina
			{
				Id = !string.IsNullOrEmpty(model.Id) ? ObjectId.Parse(model.Id) : ObjectId.GenerateNewId(DateTime.Now),
				Nome = model.Nome,
				Duracao = model.Duracao
			};
		}
	}
}

PalestraMongoDB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PalestraMongoDB.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

PalestraMongoDB/Views/Aluno/Edit.cshtml
@model PalestraMongoDB.Model.Aluno.AlunoModel

@using (Html.BeginForm("Edit", "Aluno", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.Id" />

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group label-floating">
                    @Html.LabelFor(model => model.Nome, new {@class = "control-label"})
                    @Html.TextBoxFor(model => model.Nome, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Nome, "", new {@class = "text-danger"})
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group label-floating">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Email, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

		<div class="row">
			<div class="col-lg-12">
	            <div class="form-group label-floating">
	                <label class="control-label" for="Disciplinas">Disciplinas</label>
	                <select id="Disciplinas" name="Disciplinas" asp-items="@ViewBag.Disciplinas" class="form-control">
	                	<option></option>
					</select>
	                <span class="field-validation-valid text-danger" data-valmsg-for="Disciplinas" data-valmsg-replace="true"></span>
	            </div>
			</div>
        </div>

		<div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <!--<input type="submit" value="SALVAR" class="btn btn-raised btn-primary btn-lg" />-->
					<a href="#" id="addDisciplina" class="btn btn-raised btn-primary btn-lg">Adicionar Disciplina</a>
                </div>
            </div>
        </div>

		<div id="DisciplinasTable"></div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" value="SALVAR" class="btn btn-raised btn-primary btn-lg" />
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
	    <script>
	    	$(document).ready(function () {
	    		$("#addDisciplina").click(addDisciplina)	
			});

			function addDisciplina() {
				var disciplinaId = $("#Disciplinas").val();
	
				$.ajax({
	                type:"GET",
	                contentType: "application/json",
	                url: "/Aluno/AddDisciplina/" + disciplinaId
	            }).done(disciplinaAdded);
			}

			function disciplinaAdded(data) {
				$("#DisciplinasTable").html(data);
			}
		</script>
	}
}

PalestraMongoDB/Views/Aluno/Index.cshtml
@model IEnumerable<PalestraMongoDB.Model.Aluno.AlunoModel>

<h1>Alunos</h1>

<a href="/Aluno/Edit/">Novo Aluno</a>

<table class="table" style="table-layout: fixed;">
    <thead>
        <tr>
            <th style="width: 86%">Nome</th>
            <th style="width: 10%">E-mail</th>
            <th style="width: 4%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var aluno in Model)
        {
            <tr>
                <td>
					<a href="/Aluno/Edit/@aluno.Id">
						@aluno.Nome
					</a>
				</td>
                <td>@aluno.Email</td>
                <td>
					<p>
			        	<a href="/Aluno/Delete/@aluno.Id">
			          		<span class="glyphicon glyphicon-remove"></span>
			        	</a>
			      	</p>
                </td>
            </tr>
        }
    </tbody>
</table>

PalestraMongoDB/Views/Disciplina/Edit.cshtml
@model PalestraMongoDB.Model.Disciplina.DisciplinaModel

@using (Html.BeginForm("Edit", "Disciplina", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Model.Id" />

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group label-floating">
                    @Html.LabelFor(model => model.Nome, new {@class = "control-label"})
                    @Html.TextBoxFor(model => model.Nome, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Nome, "", new {@class = "text-danger"})
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group label-floating">
                    @Html.LabelFor(model => model.Duracao, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Duracao, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Duracao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" value="SALVAR" class="btn btn-raised btn-primary btn-lg" />
                </div>
            </div>
        </div>
    </div>
}

PalestraMongoDB/Views/Disciplina/Index.cshtml
@model IEnumerable<PalestraMongoDB.Model.Disciplina.DisciplinaModel>

<h1>Disciplinas</h1>

<a href="/Disciplina/Edit/">Nova disciplina</a>

<table class="table" style="table-layout: fixed;">
    <thead>
        <tr>
            <th style="width: 86%">Nome</th>
            <th style="width: 10%">Duração</th>
            <th style="width: 4%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var disciplina in Model)
        {
            <tr>
                <td>
					<a href="/Disciplina/Edit/@disciplina.Id">
						@disciplina.Nome
					</a>
				</td>
                <td>@disciplina.Duracao</td>
                <td>
					<p>
			        	<a href="/Disciplina/Delete/@disciplina.Id">
			          		<span class="glyphicon glyphicon-remove"></span>
			        	</a>
			      	</p>
                </td>
            </tr>
        }
    </tbody>
</table>

PalestraMongoDB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

PalestraMongoDB/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PalestraMongoDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

PalestraMongoDB/Views/Shared/_DisciplinasTable.cshtml
@model IEnumerable<PalestraMongoDB.Model.Disciplina.DisciplinaModel>

<table class="table" style="table-layout: fixed;">
    <thead>
        <tr>
            <th style="width: 86%">Nome</th>
            <th style="width: 10%">Duração</th>
            <th style="width: 4%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var disciplina in Model)
        {
            <tr>
                <td>
					@disciplina.Nome
				</td>
                <td>@disciplina.Duracao</td>
            </tr>
        }
    </tbody>
</table>

PalestraMongoDB/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PalestraMongoDB</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PalestraMongoDB</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
					<li><a asp-area="" asp-controller="Disciplina" asp-action="Index">Disciplinas</a></li>
					<li><a asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - PalestraMongoDB</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>